[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip setuptools wheel",
  "cd backend/api && pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'Backend build complete'"]

[start]
cmd = "cd backend/api && gunicorn app:app --bind 0.0.0.0:$PORT"

[variables]
NIXPACKS_NO_INSTALL_PHASE = "1"
