[variables]
NIXPACKS_PYTHON_VERSION = "3.12"

[phases.setup]
nixPkgs = [
    "python312",
    "python312Packages.pip",
    "python312Packages.setuptools"
]

[phases.install]
cmds = [
    "python -m ensurepip --upgrade",
    "pip install --upgrade pip",
    "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 backend.api.app:app"