providers = ["python"]

[phases.setup]
# Ensure Python and pip are available
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
# Install backend dependencies
cmds = [
  "cd backend/api && python -m pip install --upgrade pip setuptools wheel",
  "cd backend/api && python -m pip install -r requirements.txt"
]

[phases.build]
cmds = ["echo 'No frontend build in this service'"]

[start]
cmd = "cd backend/api && gunicorn app:app --bind 0.0.0.0:$PORT"

[variables]
PORT = "5000"
