[phases.setup]
nixpkgs = ['python311', 'pip']
aptPkgs = ['python3-dev', 'gcc', 'g++']

[phases.install]
cmds = [
  'pip install --upgrade pip',
  'pip install -r backend/api/requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase completed successfully"']

[start]
cmd = 'gunicorn --chdir backend/api --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app'

[variables]
PYTHONPATH = '/app/backend'
