[phases.setup]
nixpkgs = ['python311', 'pip']
aptPkgs = ['python3-dev', 'gcc', 'g++']

[phases.install]
cmds = [
  'cd backend/api',
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build phase completed successfully"']

[start]
cmd = 'cd backend/api && gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app'

[variables]
PYTHONPATH = '/app/backend'
