[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python start.py"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { PYTHONPATH = "/app", PYTHON_VERSION = "3.12" }
